//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authority_table
    {
        public Authority_table()
        {
            this.Arranger_table = new HashSet<Arranger_table>();
            this.Student_table = new HashSet<Student_table>();
            this.Teacher_table = new HashSet<Teacher_table>();
        }
    
        public int IDAuthority { get; set; }
        public int LevelAuthority { get; set; }
    
        public virtual ICollection<Arranger_table> Arranger_table { get; set; }
        public virtual ICollection<Student_table> Student_table { get; set; }
        public virtual ICollection<Teacher_table> Teacher_table { get; set; }
    }
}
