//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building_table
    {
        public Building_table()
        {
            this.Classroom_table = new HashSet<Classroom_table>();
        }
    
        public int IDBuilding { get; set; }
        public string NameBuilding { get; set; }
        public int NumBuilding { get; set; }
        public Nullable<int> CountBuilding { get; set; }
    
        public virtual ICollection<Classroom_table> Classroom_table { get; set; }
    }
}
