//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classroom_table
    {
        public Classroom_table()
        {
            this.NewCourse_table = new HashSet<NewCourse_table>();
        }
    
        public int IDClassroom { get; set; }
        public Nullable<int> IDBuilding { get; set; }
        public int NumClassroom { get; set; }
        public Nullable<int> PeopleNumClassroom { get; set; }
    
        public virtual Building_table Building_table { get; set; }
        public virtual ICollection<NewCourse_table> NewCourse_table { get; set; }
    }
}
