//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBWebCCEntities : DbContext
    {
        public DBWebCCEntities()
            : base("name=DBWebCCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Arranger_table> Arranger_table { get; set; }
        public DbSet<Authority_table> Authority_table { get; set; }
        public DbSet<Building_table> Building_table { get; set; }
        public DbSet<Classroom_table> Classroom_table { get; set; }
        public DbSet<Course_table> Course_table { get; set; }
        public DbSet<Dorm_table> Dorm_table { get; set; }
        public DbSet<LiveDorm_table> LiveDorm_table { get; set; }
        public DbSet<NewCourse_table> NewCourse_table { get; set; }
        public DbSet<Schoolhour_table> Schoolhour_table { get; set; }
        public DbSet<Student_table> Student_table { get; set; }
        public DbSet<StudyCourse_table> StudyCourse_table { get; set; }
        public DbSet<Teacher_table> Teacher_table { get; set; }
        public DbSet<ManageClassroom_V> ManageClassroom_V { get; set; }
        public DbSet<ManageFinishedSetCourse_V> ManageFinishedSetCourse_V { get; set; }
        public DbSet<ManageLiveDorm_V> ManageLiveDorm_V { get; set; }
        public DbSet<ManageManager_V> ManageManager_V { get; set; }
        public DbSet<ManageStuChooseCourse_V> ManageStuChooseCourse_V { get; set; }
        public DbSet<ManageStudent_V> ManageStudent_V { get; set; }
        public DbSet<ManageStuGrade_V> ManageStuGrade_V { get; set; }
        public DbSet<ManageTeacher_V> ManageTeacher_V { get; set; }
        public DbSet<StudentBeginNewCourse_V> StudentBeginNewCourse_V { get; set; }
        public DbSet<StudentFinishedChooseCourse_V> StudentFinishedChooseCourse_V { get; set; }
        public DbSet<StudentGetGrade_V> StudentGetGrade_V { get; set; }
        public DbSet<TeacherFinishedGetGrade_V> TeacherFinishedGetGrade_V { get; set; }
        public DbSet<TeacherFinishedSetCourse_V> TeacherFinishedSetCourse_V { get; set; }
        public DbSet<TeacherSetStuGrade_V> TeacherSetStuGrade_V { get; set; }
        public DbSet<StudentInfo_V> StudentInfo_V { get; set; }
    }
}
