//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dorm_table
    {
        public Dorm_table()
        {
            this.LiveDorm_table = new HashSet<LiveDorm_table>();
        }
    
        public int IDDorm { get; set; }
        public int NumDorm { get; set; }
        public int CountDorm { get; set; }
    
        public virtual ICollection<LiveDorm_table> LiveDorm_table { get; set; }
    }
}
