//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCC
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiveDorm_table
    {
        public int IDLiveDorm { get; set; }
        public int IDStudent { get; set; }
        public int IDDorm { get; set; }
        public string OtherLiveDorm { get; set; }
    
        public virtual Dorm_table Dorm_table { get; set; }
        public virtual Student_table Student_table { get; set; }
    }
}
