//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManageStudent_V
    {
        public int IDStudent { get; set; }
        public string NumberStudent { get; set; }
        public string NameStudent { get; set; }
        public Nullable<int> IDAuthority { get; set; }
        public int LevelAuthority { get; set; }
        public Nullable<int> AgeStudent { get; set; }
        public int GradeStudent { get; set; }
        public Nullable<int> YearsStudent { get; set; }
        public string ImageStudent { get; set; }
        public int NumDorm { get; set; }
        public int CountDorm { get; set; }
        public string OtherLiveDorm { get; set; }
    }
}
