//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManageTeacher_V
    {
        public int IDTeacher { get; set; }
        public string NumberTeacher { get; set; }
        public string NameTeacher { get; set; }
        public string PhoneNumTeacher { get; set; }
        public string EmailTeacher { get; set; }
        public Nullable<int> IDAuthority { get; set; }
        public int LevelAuthority { get; set; }
        public Nullable<int> GradeTeacher { get; set; }
        public string SexTeacher { get; set; }
        public Nullable<int> AgeTeacher { get; set; }
        public string ImageTeacher { get; set; }
    }
}
