//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCC
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewCourse_table
    {
        public NewCourse_table()
        {
            this.StudyCourse_table = new HashSet<StudyCourse_table>();
        }
    
        public int IDNewCourse { get; set; }
        public Nullable<int> IDTeacher { get; set; }
        public Nullable<int> IDCourse { get; set; }
        public Nullable<int> IDClassroom { get; set; }
        public Nullable<int> IDSchoolhour { get; set; }
        public System.DateTime SetTimeNewCourse { get; set; }
        public System.DateTime BeginTimeNewCourse { get; set; }
        public Nullable<int> StateNewCourse { get; set; }
        public Nullable<int> AccommodateNewCourse { get; set; }
        public int NatureNewCourse { get; set; }
    
        public virtual Classroom_table Classroom_table { get; set; }
        public virtual Course_table Course_table { get; set; }
        public virtual Teacher_table Teacher_table { get; set; }
        public virtual Schoolhour_table Schoolhour_table { get; set; }
        public virtual ICollection<StudyCourse_table> StudyCourse_table { get; set; }
    }
}
