//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schoolhour_table
    {
        public Schoolhour_table()
        {
            this.NewCourse_table = new HashSet<NewCourse_table>();
        }
    
        public int IDSchoolhour { get; set; }
        public int TimesectionSchoolhour { get; set; }
        public int TimesectionSchoolhourDetail { get; set; }
    
        public virtual ICollection<NewCourse_table> NewCourse_table { get; set; }
    }
}
