//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCC
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyCourse_table
    {
        public int IDStudyCourse { get; set; }
        public Nullable<int> IDStudent { get; set; }
        public Nullable<int> IDNewCourse { get; set; }
        public int GradeStudyCourse { get; set; }
    
        public virtual NewCourse_table NewCourse_table { get; set; }
        public virtual Student_table Student_table { get; set; }
    }
}
