//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_table
    {
        public Student_table()
        {
            this.LiveDorm_table = new HashSet<LiveDorm_table>();
            this.StudyCourse_table = new HashSet<StudyCourse_table>();
        }
    
        public int IDStudent { get; set; }
        public Nullable<int> IDAuthority { get; set; }
        public string NumberStudent { get; set; }
        public string NameStudent { get; set; }
        public Nullable<int> AgeStudent { get; set; }
        public string PasscodeStudent { get; set; }
        public int GradeStudent { get; set; }
        public Nullable<int> YearsStudent { get; set; }
        public string ImageStudent { get; set; }
    
        public virtual Authority_table Authority_table { get; set; }
        public virtual ICollection<LiveDorm_table> LiveDorm_table { get; set; }
        public virtual ICollection<StudyCourse_table> StudyCourse_table { get; set; }
    }
}
